//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfClient.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Fair.
        /// </summary>
        public static string About_AppName {
            get {
                return ResourceManager.GetString("About_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string About_Authors {
            get {
                return ResourceManager.GetString("About_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was developed by Stefan Karać and Milica Stanković, third-year students at the Faculty of Technical Sciences in Novi Sad, Computer Science and Automation..
        /// </summary>
        public static string About_Authors_Text {
            get {
                return ResourceManager.GetString("About_Authors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string About_Close {
            get {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for managing visitors, authors and books at the book fair. Desktop application intended for fair staff. It enables adding, editing and deleting data, as well as viewing all entered information..
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Autor_Adresa {
            get {
                return ResourceManager.GetString("Autor_Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Autor_DatumRodjenja {
            get {
                return ResourceManager.GetString("Autor_DatumRodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Autor_Email {
            get {
                return ResourceManager.GetString("Autor_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of experience.
        /// </summary>
        public static string Autor_GodIskustva {
            get {
                return ResourceManager.GetString("Autor_GodIskustva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Autor_Ime {
            get {
                return ResourceManager.GetString("Autor_Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Autor_Prezime {
            get {
                return ResourceManager.GetString("Autor_Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Autor_Telefon {
            get {
                return ResourceManager.GetString("Autor_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show visitors with wishlist books by the author.
        /// </summary>
        public static string Btn_GridAutori {
            get {
                return ResourceManager.GetString("Btn_GridAutori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display book authors in the visitor&apos;s wish list.
        /// </summary>
        public static string Btn_GridPosetioci {
            get {
                return ResourceManager.GetString("Btn_GridPosetioci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; First.
        /// </summary>
        public static string btnFirstPageAutori {
            get {
                return ResourceManager.GetString("btnFirstPageAutori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; First.
        /// </summary>
        public static string btnFirstPageKnjige {
            get {
                return ResourceManager.GetString("btnFirstPageKnjige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; First.
        /// </summary>
        public static string btnFirstPagePosetioci {
            get {
                return ResourceManager.GetString("btnFirstPagePosetioci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last &gt;.
        /// </summary>
        public static string btnLastPageAutori {
            get {
                return ResourceManager.GetString("btnLastPageAutori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last &gt;.
        /// </summary>
        public static string btnLastPageKnjige {
            get {
                return ResourceManager.GetString("btnLastPageKnjige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last &gt;.
        /// </summary>
        public static string btnLastPagePosetioci {
            get {
                return ResourceManager.GetString("btnLastPagePosetioci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Knjiga_Autori {
            get {
                return ResourceManager.GetString("Knjiga_Autori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string Knjiga_BrStrana {
            get {
                return ResourceManager.GetString("Knjiga_BrStrana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Knjiga_Cena {
            get {
                return ResourceManager.GetString("Knjiga_Cena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of issue.
        /// </summary>
        public static string Knjiga_GodIzdavanja {
            get {
                return ResourceManager.GetString("Knjiga_GodIzdavanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Knjiga_ISBN {
            get {
                return ResourceManager.GetString("Knjiga_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Knjiga_Izdavac {
            get {
                return ResourceManager.GetString("Knjiga_Izdavac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the book.
        /// </summary>
        public static string Knjiga_Naziv {
            get {
                return ResourceManager.GetString("Knjiga_Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Knjiga_Zanr {
            get {
                return ResourceManager.GetString("Knjiga_Zanr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        public static string Kolona_IDAutora {
            get {
                return ResourceManager.GetString("Kolona_IDAutora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Fair.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string Menu_Analitika {
            get {
                return ResourceManager.GetString("Menu_Analitika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Analytics.
        /// </summary>
        public static string Menu_Analitika_Izdavaci {
            get {
                return ResourceManager.GetString("Menu_Analitika_Izdavaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics for two books.
        /// </summary>
        public static string Menu_Analitika_Knjige {
            get {
                return ResourceManager.GetString("Menu_Analitika_Knjige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_Edit_Delete {
            get {
                return ResourceManager.GetString("Menu_Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_Edit_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open .
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Menu_File_Open_Autori {
            get {
                return ResourceManager.GetString("Menu_File_Open_Autori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Menu_File_Open_Izdavaci {
            get {
                return ResourceManager.GetString("Menu_File_Open_Izdavaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Menu_File_Open_Knjige {
            get {
                return ResourceManager.GetString("Menu_File_Open_Knjige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string Menu_File_Open_Posetioci {
            get {
                return ResourceManager.GetString("Menu_File_Open_Posetioci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the author?.
        /// </summary>
        public static string Msg_ConfirmDeleteAuthor {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the book?.
        /// </summary>
        public static string Msg_ConfirmDeleteBook {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the visitor?.
        /// </summary>
        public static string Msg_ConfirmDeleteVisitor {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not loaded..
        /// </summary>
        public static string Msg_DataNotLoaded {
            get {
                return ResourceManager.GetString("Msg_DataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data has been saved successfully!.
        /// </summary>
        public static string Msg_DataSaved {
            get {
                return ResourceManager.GetString("Msg_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Author.
        /// </summary>
        public static string Msg_DeleteAuthorTitle {
            get {
                return ResourceManager.GetString("Msg_DeleteAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Book.
        /// </summary>
        public static string Msg_DeleteBookTitle {
            get {
                return ResourceManager.GetString("Msg_DeleteBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Visitor.
        /// </summary>
        public static string Msg_DeleteVisitorTitle {
            get {
                return ResourceManager.GetString("Msg_DeleteVisitorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving data.
        /// </summary>
        public static string Msg_ErrorSavingData {
            get {
                return ResourceManager.GetString("Msg_ErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_ErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authors with books on this visitor&apos;s wishlist..
        /// </summary>
        public static string Msg_NoAuthorsForVisitorWishlist {
            get {
                return ResourceManager.GetString("Msg_NoAuthorsForVisitorWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No visitors have this author&apos;s books on their wishlist..
        /// </summary>
        public static string Msg_NoVisitorsWithAuthorsBooks {
            get {
                return ResourceManager.GetString("Msg_NoVisitorsWithAuthorsBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Msg_OK {
            get {
                return ResourceManager.GetString("Msg_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Msg_SaveTitle {
            get {
                return ResourceManager.GetString("Msg_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an author from the table..
        /// </summary>
        public static string Msg_SelectAuthor {
            get {
                return ResourceManager.GetString("Msg_SelectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an author to edit..
        /// </summary>
        public static string Msg_SelectAuthorForEdit {
            get {
                return ResourceManager.GetString("Msg_SelectAuthorForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a book from the table..
        /// </summary>
        public static string Msg_SelectBook {
            get {
                return ResourceManager.GetString("Msg_SelectBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a book to edit..
        /// </summary>
        public static string Msg_SelectBookForEdit {
            get {
                return ResourceManager.GetString("Msg_SelectBookForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a visitor from the table..
        /// </summary>
        public static string Msg_SelectVisitor {
            get {
                return ResourceManager.GetString("Msg_SelectVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a visitor to edit..
        /// </summary>
        public static string Msg_SelectVisitorForEdit {
            get {
                return ResourceManager.GetString("Msg_SelectVisitorForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Msg_WarningTitle {
            get {
                return ResourceManager.GetString("Msg_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Posetilac_Adresa {
            get {
                return ResourceManager.GetString("Posetilac_Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership card.
        /// </summary>
        public static string Posetilac_ClanskaKarta {
            get {
                return ResourceManager.GetString("Posetilac_ClanskaKarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of membership.
        /// </summary>
        public static string Posetilac_GodinaClanstva {
            get {
                return ResourceManager.GetString("Posetilac_GodinaClanstva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Posetilac_Ime {
            get {
                return ResourceManager.GetString("Posetilac_Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Posetilac_Prezime {
            get {
                return ResourceManager.GetString("Posetilac_Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average grade.
        /// </summary>
        public static string Posetilac_ProsecnaOcena {
            get {
                return ResourceManager.GetString("Posetilac_ProsecnaOcena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Posetilac_Status {
            get {
                return ResourceManager.GetString("Posetilac_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Fair.
        /// </summary>
        public static string Status_BookFair {
            get {
                return ResourceManager.GetString("Status_BookFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string Status_PageInfo {
            get {
                return ResourceManager.GetString("Status_PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Tab_Autori {
            get {
                return ResourceManager.GetString("Tab_Autori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Tab_Knjige {
            get {
                return ResourceManager.GetString("Tab_Knjige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string Tab_Posetioci {
            get {
                return ResourceManager.GetString("Tab_Posetioci", resourceCulture);
            }
        }
    }
}
